---
abstract: 'Create a full-screen window with Xlib'
author:
  - 'Stephen Nelson, E<lt>stephenenelson@mac.com<gt>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: X11-FullScreen
provides:
  X11::FullScreen:
    file: lib/X11/FullScreen.pm
    version: 0.991
requires:
  XSLoader: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.991
